#
# rename this file to application.yml before build/run
#


datasource:

  # H2
  h2:
    url: jdbc:h2:file:~/test
    username: sa
    password:

  # SQLServer
  sqlserver:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TestDB;user=SA;password=<YourStrong@Passw0rd>;

  # Oracle
  oracle:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/NETS_LOCAL
    #      jdbc:oracle:thin:@//HOSTNAME:PORT/SERVICENAME
    # example: jdbc.url=jdbc:oracle:thin:@//dfw-vu-devodb1.uat.svbank.com:1526/DEVOPSPOCDB
    username: NETS
    password: password

bitronix.tm:
  serverId: myapp
  journal.disk:
    logPart1Filename: logPart1Filename
    logPart2Filename: logPart2Filename

#logging.level.org.springframework.jdbc.datasource: DEBUG
#logging.level.org.springframework.transaction: DEBUG
#logging.level.org.springframework.transaction.interceptor: TRACE

logging.level.bitronix: DEBUG
logging.level.org.springframework.jdbc.core: DEBUG
